# This file is part of NSDotPy, a wrapper around requests that makes interacting
# with the HTML nationstates.net site legally and efficiently easier.
#
# NSDotPy is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License
# as published by the Free Software Foundation either version
# 3 of the License, or (at your option) any later version.
#
# NSDotPy is distributed in the hope that it will be useful but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with NSDotPy. If not, see <https://www.gnu.org/licenses/>.
tags = [
    "anarchist",
    "anime",
    "anti-capitalist",
    "anti-communist",
    "anti-fascist",
    "anti-general_assembly",
    "anti-security_council",
    "anti-world_assembly",
    "capitalist",
    "casual",
    "colony",
    "communist",
    "conservative",
    "cyberpunk",
    "defender",
    "democratic",
    "eco-friendly",
    "egalitarian",
    "embassy_collector",
    "f7er",
    "ft_ftl",
    "ft_ftli",
    "ft_stl",
    "fandom",
    "fantasy_tech",
    "fascist",
    "feminist",
    "free_trade",
    "future_tech",
    "game_player",
    "general_assembly",
    "generalite",
    "human-only",
    "imperialist",
    "independent",
    "industrial",
    "international_federalist",
    "invader",
    "isolationist",
    "issues_player",
    "jump_point",
    "lgbt",
    "liberal",
    "libertarian",
    "magical",
    "map",
    "mercenary",
    "modern_tech",
    "monarchist",
    "multi-species",
    "national_sovereigntist",
    "neutral",
    "non-english",
    "offsite_chat",
    "offsite_forums",
    "outer_space",
    "p2tm",
    "pacifist",
    "parody",
    "past_tech",
    "patriarchal",
    "post_apocalyptic",
    "post-modern_tech",
    "puppet_storage",
    "regional_government",
    "religious",
    "role_player",
    "security_council",
    "serious",
    "silly",
    "snarky",
    "social",
    "socialist",
    "sports",
    "steampunk",
    "surreal",
    "theocratic",
    "totalitarian",
    "trading_cards",
    "video_game",
    "world_assembly",
]
